alert ("nous avons piraté votre telephone")
alert ("اضغط حسنا")
alert ("جاري نقل البيانت")
alert ("تم قل البيانات بنجاح")
alert ("تم اختراق هاتفك بنجاح")
alert ("haya tsb7o bkhir amno wla la makan madakhalni")
alert ("iiiw ")
alert ("7chithalkom")
alert (" rani nz39 ro7o  trgdo ")
alert ("3jbtkom ?")
alert ("a mimir")
alret ("sayi bye")